name: Version Bump

on:
  release:
    types: [created]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Update version
      run: |
        VERSION=${{ github.event.release.tag_name }}
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        
        # Update version in __init__.py
        sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" usac_velodata/__init__.py
        
        # Update version in setup.py
        sed -i "s/version=\".*\",/version=\"$VERSION\",/" setup.py
    
    - name: Commit and push version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add usac_velodata/__init__.py setup.py
        git commit -m "Bump version to ${{ github.event.release.tag_name }}"
        git push 